services:
  db:
    container_name: edusync_cat_db
    image: docker.io/library/postgres:latest
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER:-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-root}
      POSTGRES_DB: ${DB_NAME:-edusync_db}
    ports:
      - "5432:5432"
    networks:
      - edusync-net

networks:
  edusync-net: